baseURL = 'https://josevu.com/'
languageCode = 'en-us'
title = 'Jose Vu Blog'
theme = "poison"

[Params]
  brand = "Jose Vu"
  description = "Welcome to my blog"
  dark_mode = true
  
  [Params.Author]
    name = "Jose Vu"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"